import Head from "next/head";
import { Inter } from "next/font/google";
import { useState } from "react";
import TextInput from "@/components/TextInput";
import SubmitButton from "@/components/SubmitButton";
import ResponseDisplay from "@/components/ResponseDisplay";
import useApi from "@/hooks/useApi";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [inputValue, setInputValue] = useState("");
  const [submitValue, setSubmitValue] = useState("");
  const [userMessages, setUserMessages] = useState([]);
  const [assistantMessages, setAssistantMessages] = useState([]);
  const { data, error, loading } = useApi(
    "/api/openai",
    "POST",
    submitValue,
    userMessages,
    assistantMessages
  );

  const handleSubmit = (event) => {
    event.preventDefault();
    setSubmitValue(inputValue);
    setUserMessages([...userMessages, inputValue]);

    if (data?.result) {
      setAssistantMessages([...assistantMessages, data.result]);
    }
  };

  const handleInputChange = (event) => {
    setInputValue(event.target.value);
  };

  return (
    <>
      <Head>
        <title>NextJS OpenAI Boilerplate</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col max-w-5xl mx-auto px-10">
        <h1 className="text-3xl font-bold mt-10 text-black">
          Tweet Generator AI
        </h1>
        <p className="text-sm font-thin text-black opacity-80">
          Powerd by Nextjs openai boilerplate
        </p>

        <p className="text-white opacity-75 mt-5 flex flex-col">
          <span>Prompt {!inputValue && <span>Example: </span>}</span>
          {inputValue ? (
            <span>{inputValue}</span>
          ) : (
            <span>
              "Generate a tweet for a mystery story for adults with a theme of
              revenge that conveys the message that actions have consequences.
              The story should have a serious and dramatic tone and include a
              detective character with a troubled past and a vengeful antagonist
              with a secret motive. It should be set in a small town in the
              present day."
            </span>
          )}
        </p>
        <form>
          <ResponseDisplay data={data} error={error} loading={loading} />
          <TextInput value={inputValue} onChange={handleInputChange} />
          <SubmitButton onClick={handleSubmit} disabled={loading} />
        </form>
      </main>
    </>
  );
}
